### ISSUE TITLE
Error 429 - We have detected excessive traffic from your account, your access to the service has been limited for a few hours.

### ISSUE THREAD

**Issue by BS-GIFHUB** [Black-Thunder/ioBroker.melcloud#672]
Hello,

adapter worked till yesterday fine for me. Now I lost the connection over a day and then I'm blocked by the Melcloud because of too many tries to log in. With that the adapter doesn't work any more.

Any help ?

Bernhard

**Comment by BS-GIFHUB** [comment]
MELCloud
We have detected excessive traffic from your account, your access to the service has been limited for a few hours.

That's now the problem

Bernhard

**Comment by vvfrwl** [comment]
I've checked. 
The same problem ).
I had 1min pooling interval.

**Comment by vvfrwl** [comment]
MELCloud allows several accounts for one cabinet.
I guess they check traffic per user.
Adapter may distribute traffic between several accounts if long intervals are not convenient.

**Comment by BS-GIFHUB** [comment]
I have also an homebridge adapter for the melcoud named "homebridge-melcloud-control". This adapter still works also after melcoud locked my account. So my opinion on this positiv behavior is that the adapter is only locked in once and holds the connection over the time. This adapter seems to work with multiple logins and so the melcloud blocked the user. May me that this is a way for a modification to avoid this problem.

**Comment by Black-Thunder** [comment]
@BS-GIFHUB @vvfrwl 
I've just pushed some changes to GitHub to reuse the same login/context key for 12 hours before getting a new one.

Please update your version directly from GitHub and report back if you're getting blocked again after some time and if yes which interval you're using.

**Comment by BS-GIFHUB** [comment]
Hello, okay thanks. I did an update with https://github.com/Black-Thunder/ioBroker.melcloud but still gets the same version 1.3.6 .
Did test it because its not a new version number.

**Comment by BS-GIFHUB** [comment]
didn't test it. sorry

**Comment by Black-Thunder** [comment]
That's correct, the version number is the same for now. You should see new log entries every run if you switch the log level to "Debug".

```
Next polling interval: Using the same (old) context key.
```

After 12 hours:

```
Context key invalidated. Getting a new one for the next polling interval.
Next polling interval: Getting a new context key.
```

**Comment by Black-Thunder** [comment]
I've just published a new release v1.3.7 (soon in latest repository) which includes a few changes to reduce the number of server calls. Minimum pollinginterval is now 5 minutes.
Please try that version and report if throttling/blocking still occurs.

**Comment by Black-Thunder** [comment]
@BS-GIFHUB @vvfrwl How is your experience with v1.3.7 so far?

**Comment by vvfrwl** [comment]
It looks good, but the 5-minute pooling interval worked fine before version 1.3.7.

**Comment by BS-GIFHUB** [comment]
Hi, Thanks in my case it works now for 3 days. I used always the 5 minutes period and got an failure because of additional account use for homebridge. Now I use homebridge with an different username and the iobroker adapter with v1.3.7 and this works for me.

**Comment by Black-Thunder** [comment]
Thanks for the quick feedback. This version will move to stable repo soon then.

**Comment by vvfrwl** [comment]
It is sensible to include a notification for the polling interval settings. 
For example, "it is advisable to use a pooling interval of more than 5 minutes to prevent the account from being blocked".

**Comment by Black-Thunder** [comment]
With 1.3.7 the minimum polling interval is already raised to 5 minutes, so you can't set it lower than that.

**Comment by vvfrwl** [comment]
I got it after my message ).

**Comment by Chris9463773** [comment]
I still have the Problem. My version is 1.3.7 an i set the pollinginterval to 60 minutes.
After starting the Adapter instantly this Error appears

<html><body>

melcloud.0 | 2024-02-19 18:33:14.942 | error | You  have probably been rate limited by the MELCloud servers because of too  much requests. Stop the adapter for a few hours, increase the polling  interval in the settings and try again later.
-- | -- | -- | --
melcloud.0 | 2024-02-19 18:33:14.941 | error | AxiosError: Request failed with status code 429
melcloud.0 | 2024-02-19 18:33:14.939 | error | There was a problem sending login to: https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin


</body>
</html>

The Adapter was paused for 8 Hours.

What can i do?

**Comment by Black-Thunder** [comment]
Are you able to login to https://app.melcloud.com/ or is your account also locked there?

**Comment by Chris9463773** [comment]
It is also blocked. But the App works fine

**Comment by Black-Thunder** [comment]
As long as you can't login to the web portal, the adapter will also not work as it uses the same method.
Your only option is to stop the adapter and wait again, maybe this time a whole day before trying again. Also make sure that you don't use any other similar plugin (Home Assistant etc.).
